server:
  port: 8080
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 2s
      routes:
        - id: system1 //라우팅 설정
          uri: http://localhost:8081/ // http://localhost:8080/system1/ 이 호출된다면 http://localhost:8081/system1/이 호출된다.
          predicates: //조건 검사
            - Path=/service1/**
          filters: //gateway에서 받은 요청 수정
            - name: ClientFilter


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}